version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: wechat_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=wechat_crawler
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=wechat123
    networks:
      - wechat_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: wechat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass wechat123
    networks:
      - wechat_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "wechat123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: wechat_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=wechat123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:wechat123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=wechat123
    networks:
      - wechat_network
    depends_on:
      mongodb:
        condition: service_healthy

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: wechat_redis_commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:wechat123
    networks:
      - wechat_network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  wechat_network:
    driver: bridge